package com.qf.entity;

public class Address {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.addressId
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    private Integer addressid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.province
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.city
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.county
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.recriverPhone
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    private String recriverphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.recriverName
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    private String recrivername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.specificAddress
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    private String specificaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.isDefauit
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    private Integer isdefauit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.userId
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.addressId
     *
     * @return the value of address.addressId
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    public Integer getAddressid() {
        return addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.addressId
     *
     * @param addressid the value for address.addressId
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    public void setAddressid(Integer addressid) {
        this.addressid = addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.province
     *
     * @return the value of address.province
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.province
     *
     * @param province the value for address.province
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.city
     *
     * @return the value of address.city
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.city
     *
     * @param city the value for address.city
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.county
     *
     * @return the value of address.county
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.county
     *
     * @param county the value for address.county
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    public void setCounty(String county) {
        this.county = county == null ? null : county.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.recriverPhone
     *
     * @return the value of address.recriverPhone
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    public String getRecriverphone() {
        return recriverphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.recriverPhone
     *
     * @param recriverphone the value for address.recriverPhone
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    public void setRecriverphone(String recriverphone) {
        this.recriverphone = recriverphone == null ? null : recriverphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.recriverName
     *
     * @return the value of address.recriverName
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    public String getRecrivername() {
        return recrivername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.recriverName
     *
     * @param recrivername the value for address.recriverName
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    public void setRecrivername(String recrivername) {
        this.recrivername = recrivername == null ? null : recrivername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.specificAddress
     *
     * @return the value of address.specificAddress
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    public String getSpecificaddress() {
        return specificaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.specificAddress
     *
     * @param specificaddress the value for address.specificAddress
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    public void setSpecificaddress(String specificaddress) {
        this.specificaddress = specificaddress == null ? null : specificaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.isDefauit
     *
     * @return the value of address.isDefauit
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    public Integer getIsdefauit() {
        return isdefauit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.isDefauit
     *
     * @param isdefauit the value for address.isDefauit
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    public void setIsdefauit(Integer isdefauit) {
        this.isdefauit = isdefauit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.userId
     *
     * @return the value of address.userId
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.userId
     *
     * @param userid the value for address.userId
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
}