package com.qf.entity;

public class Area {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.id
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.area_name
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    private String areaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.area_code
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.area_parent_id
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    private Integer areaParentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.id
     *
     * @return the value of area.id
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.id
     *
     * @param id the value for area.id
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.area_name
     *
     * @return the value of area.area_name
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.area_name
     *
     * @param areaName the value for area.area_name
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.area_code
     *
     * @return the value of area.area_code
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.area_code
     *
     * @param areaCode the value for area.area_code
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.area_parent_id
     *
     * @return the value of area.area_parent_id
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    public Integer getAreaParentId() {
        return areaParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.area_parent_id
     *
     * @param areaParentId the value for area.area_parent_id
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    public void setAreaParentId(Integer areaParentId) {
        this.areaParentId = areaParentId;
    }
}