package com.qf.entity;

public class Productappraise {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productappraise.accessId
     *
     * @mbggenerated Tue Apr 16 16:28:15 CST 2019
     */
    private Integer accessid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productappraise.accessGrade
     *
     * @mbggenerated Tue Apr 16 16:28:15 CST 2019
     */
    private Integer accessgrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productappraise.accessText
     *
     * @mbggenerated Tue Apr 16 16:28:15 CST 2019
     */
    private String accesstext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productappraise.userId
     *
     * @mbggenerated Tue Apr 16 16:28:15 CST 2019
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productappraise.productId
     *
     * @mbggenerated Tue Apr 16 16:28:15 CST 2019
     */
    private Integer productid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productappraise.accessId
     *
     * @return the value of productappraise.accessId
     *
     * @mbggenerated Tue Apr 16 16:28:15 CST 2019
     */
    public Integer getAccessid() {
        return accessid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productappraise.accessId
     *
     * @param accessid the value for productappraise.accessId
     *
     * @mbggenerated Tue Apr 16 16:28:15 CST 2019
     */
    public void setAccessid(Integer accessid) {
        this.accessid = accessid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productappraise.accessGrade
     *
     * @return the value of productappraise.accessGrade
     *
     * @mbggenerated Tue Apr 16 16:28:15 CST 2019
     */
    public Integer getAccessgrade() {
        return accessgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productappraise.accessGrade
     *
     * @param accessgrade the value for productappraise.accessGrade
     *
     * @mbggenerated Tue Apr 16 16:28:15 CST 2019
     */
    public void setAccessgrade(Integer accessgrade) {
        this.accessgrade = accessgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productappraise.accessText
     *
     * @return the value of productappraise.accessText
     *
     * @mbggenerated Tue Apr 16 16:28:15 CST 2019
     */
    public String getAccesstext() {
        return accesstext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productappraise.accessText
     *
     * @param accesstext the value for productappraise.accessText
     *
     * @mbggenerated Tue Apr 16 16:28:15 CST 2019
     */
    public void setAccesstext(String accesstext) {
        this.accesstext = accesstext == null ? null : accesstext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productappraise.userId
     *
     * @return the value of productappraise.userId
     *
     * @mbggenerated Tue Apr 16 16:28:15 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productappraise.userId
     *
     * @param userid the value for productappraise.userId
     *
     * @mbggenerated Tue Apr 16 16:28:15 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productappraise.productId
     *
     * @return the value of productappraise.productId
     *
     * @mbggenerated Tue Apr 16 16:28:15 CST 2019
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productappraise.productId
     *
     * @param productid the value for productappraise.productId
     *
     * @mbggenerated Tue Apr 16 16:28:15 CST 2019
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }
}