package com.qf.entity;

public class Productshopping {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productshopping.shoppingId
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    private Integer shoppingid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productshopping.shoppingNumber
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    private Integer shoppingnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productshopping.productId
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    private Integer productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productshopping.userId
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productshopping.shoppingId
     *
     * @return the value of productshopping.shoppingId
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    public Integer getShoppingid() {
        return shoppingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productshopping.shoppingId
     *
     * @param shoppingid the value for productshopping.shoppingId
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    public void setShoppingid(Integer shoppingid) {
        this.shoppingid = shoppingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productshopping.shoppingNumber
     *
     * @return the value of productshopping.shoppingNumber
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    public Integer getShoppingnumber() {
        return shoppingnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productshopping.shoppingNumber
     *
     * @param shoppingnumber the value for productshopping.shoppingNumber
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    public void setShoppingnumber(Integer shoppingnumber) {
        this.shoppingnumber = shoppingnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productshopping.productId
     *
     * @return the value of productshopping.productId
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productshopping.productId
     *
     * @param productid the value for productshopping.productId
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productshopping.userId
     *
     * @return the value of productshopping.userId
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productshopping.userId
     *
     * @param userid the value for productshopping.userId
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
}