package com.qf.entity;

public class Productappraise {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productappraise.appraiseId
     *
     * @mbggenerated Sun Apr 14 15:07:44 CST 2019
     */
    private Integer appraiseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productappraise.userName
     *
     * @mbggenerated Sun Apr 14 15:07:44 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productappraise.headUrl
     *
     * @mbggenerated Sun Apr 14 15:07:44 CST 2019
     */
    private String headurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productappraise.accessGrade
     *
     * @mbggenerated Sun Apr 14 15:07:44 CST 2019
     */
    private Integer accessgrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productappraise.productType
     *
     * @mbggenerated Sun Apr 14 15:07:44 CST 2019
     */
    private String producttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productappraise.accessText
     *
     * @mbggenerated Sun Apr 14 15:07:44 CST 2019
     */
    private String accesstext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productappraise.productClassId
     *
     * @mbggenerated Sun Apr 14 15:07:44 CST 2019
     */
    private Integer productclassid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productappraise.appraiseId
     *
     * @return the value of productappraise.appraiseId
     *
     * @mbggenerated Sun Apr 14 15:07:44 CST 2019
     */
    public Integer getAppraiseid() {
        return appraiseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productappraise.appraiseId
     *
     * @param appraiseid the value for productappraise.appraiseId
     *
     * @mbggenerated Sun Apr 14 15:07:44 CST 2019
     */
    public void setAppraiseid(Integer appraiseid) {
        this.appraiseid = appraiseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productappraise.userName
     *
     * @return the value of productappraise.userName
     *
     * @mbggenerated Sun Apr 14 15:07:44 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productappraise.userName
     *
     * @param username the value for productappraise.userName
     *
     * @mbggenerated Sun Apr 14 15:07:44 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productappraise.headUrl
     *
     * @return the value of productappraise.headUrl
     *
     * @mbggenerated Sun Apr 14 15:07:44 CST 2019
     */
    public String getHeadurl() {
        return headurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productappraise.headUrl
     *
     * @param headurl the value for productappraise.headUrl
     *
     * @mbggenerated Sun Apr 14 15:07:44 CST 2019
     */
    public void setHeadurl(String headurl) {
        this.headurl = headurl == null ? null : headurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productappraise.accessGrade
     *
     * @return the value of productappraise.accessGrade
     *
     * @mbggenerated Sun Apr 14 15:07:44 CST 2019
     */
    public Integer getAccessgrade() {
        return accessgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productappraise.accessGrade
     *
     * @param accessgrade the value for productappraise.accessGrade
     *
     * @mbggenerated Sun Apr 14 15:07:44 CST 2019
     */
    public void setAccessgrade(Integer accessgrade) {
        this.accessgrade = accessgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productappraise.productType
     *
     * @return the value of productappraise.productType
     *
     * @mbggenerated Sun Apr 14 15:07:44 CST 2019
     */
    public String getProducttype() {
        return producttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productappraise.productType
     *
     * @param producttype the value for productappraise.productType
     *
     * @mbggenerated Sun Apr 14 15:07:44 CST 2019
     */
    public void setProducttype(String producttype) {
        this.producttype = producttype == null ? null : producttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productappraise.accessText
     *
     * @return the value of productappraise.accessText
     *
     * @mbggenerated Sun Apr 14 15:07:44 CST 2019
     */
    public String getAccesstext() {
        return accesstext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productappraise.accessText
     *
     * @param accesstext the value for productappraise.accessText
     *
     * @mbggenerated Sun Apr 14 15:07:44 CST 2019
     */
    public void setAccesstext(String accesstext) {
        this.accesstext = accesstext == null ? null : accesstext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productappraise.productClassId
     *
     * @return the value of productappraise.productClassId
     *
     * @mbggenerated Sun Apr 14 15:07:44 CST 2019
     */
    public Integer getProductclassid() {
        return productclassid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productappraise.productClassId
     *
     * @param productclassid the value for productappraise.productClassId
     *
     * @mbggenerated Sun Apr 14 15:07:44 CST 2019
     */
    public void setProductclassid(Integer productclassid) {
        this.productclassid = productclassid;
    }
}