package com.qf.entity;

import java.math.BigDecimal;

public class Productinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productinfo.productId
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    private Integer productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productinfo.productName
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    private String productname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productinfo.productMsg
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    private String productmsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productinfo.productStock
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    private Integer productstock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productinfo.productPrice
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    private BigDecimal productprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productinfo.advertUrl
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    private String adverturl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productinfo.productClassId
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    private Integer productclassid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productinfo.provider
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    private String provider;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productinfo.productId
     *
     * @return the value of productinfo.productId
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productinfo.productId
     *
     * @param productid the value for productinfo.productId
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productinfo.productName
     *
     * @return the value of productinfo.productName
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public String getProductname() {
        return productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productinfo.productName
     *
     * @param productname the value for productinfo.productName
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public void setProductname(String productname) {
        this.productname = productname == null ? null : productname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productinfo.productMsg
     *
     * @return the value of productinfo.productMsg
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public String getProductmsg() {
        return productmsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productinfo.productMsg
     *
     * @param productmsg the value for productinfo.productMsg
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public void setProductmsg(String productmsg) {
        this.productmsg = productmsg == null ? null : productmsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productinfo.productStock
     *
     * @return the value of productinfo.productStock
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public Integer getProductstock() {
        return productstock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productinfo.productStock
     *
     * @param productstock the value for productinfo.productStock
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public void setProductstock(Integer productstock) {
        this.productstock = productstock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productinfo.productPrice
     *
     * @return the value of productinfo.productPrice
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public BigDecimal getProductprice() {
        return productprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productinfo.productPrice
     *
     * @param productprice the value for productinfo.productPrice
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public void setProductprice(BigDecimal productprice) {
        this.productprice = productprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productinfo.advertUrl
     *
     * @return the value of productinfo.advertUrl
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public String getAdverturl() {
        return adverturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productinfo.advertUrl
     *
     * @param adverturl the value for productinfo.advertUrl
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public void setAdverturl(String adverturl) {
        this.adverturl = adverturl == null ? null : adverturl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productinfo.productClassId
     *
     * @return the value of productinfo.productClassId
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public Integer getProductclassid() {
        return productclassid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productinfo.productClassId
     *
     * @param productclassid the value for productinfo.productClassId
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public void setProductclassid(Integer productclassid) {
        this.productclassid = productclassid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productinfo.provider
     *
     * @return the value of productinfo.provider
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public String getProvider() {
        return provider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productinfo.provider
     *
     * @param provider the value for productinfo.provider
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public void setProvider(String provider) {
        this.provider = provider == null ? null : provider.trim();
    }
}