package com.qf.entity;

public class Productpicture {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productpicture.pictureId
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    private Integer pictureid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productpicture.pictureUrl
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    private String pictureurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productpicture.pictureType
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    private Integer picturetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productpicture.productId
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    private Integer productid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productpicture.pictureId
     *
     * @return the value of productpicture.pictureId
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    public Integer getPictureid() {
        return pictureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productpicture.pictureId
     *
     * @param pictureid the value for productpicture.pictureId
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    public void setPictureid(Integer pictureid) {
        this.pictureid = pictureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productpicture.pictureUrl
     *
     * @return the value of productpicture.pictureUrl
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    public String getPictureurl() {
        return pictureurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productpicture.pictureUrl
     *
     * @param pictureurl the value for productpicture.pictureUrl
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    public void setPictureurl(String pictureurl) {
        this.pictureurl = pictureurl == null ? null : pictureurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productpicture.pictureType
     *
     * @return the value of productpicture.pictureType
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    public Integer getPicturetype() {
        return picturetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productpicture.pictureType
     *
     * @param picturetype the value for productpicture.pictureType
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    public void setPicturetype(Integer picturetype) {
        this.picturetype = picturetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productpicture.productId
     *
     * @return the value of productpicture.productId
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productpicture.productId
     *
     * @param productid the value for productpicture.productId
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }
}