package com.qf.entity;

public class Productcollection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productcollection.collectionId
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    private Integer collectionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productcollection.productId
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    private Integer productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productcollection.userId
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productcollection.collectionId
     *
     * @return the value of productcollection.collectionId
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    public Integer getCollectionid() {
        return collectionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productcollection.collectionId
     *
     * @param collectionid the value for productcollection.collectionId
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    public void setCollectionid(Integer collectionid) {
        this.collectionid = collectionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productcollection.productId
     *
     * @return the value of productcollection.productId
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productcollection.productId
     *
     * @param productid the value for productcollection.productId
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productcollection.userId
     *
     * @return the value of productcollection.userId
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productcollection.userId
     *
     * @param userid the value for productcollection.userId
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
}