package com.qf.entity;

public class ProInfoType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_info_type.info_Type_Id
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    private Integer infoTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_info_type.productId
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    private Integer productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_info_type.typeId
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    private Integer typeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_info_type.info_Type_Id
     *
     * @return the value of pro_info_type.info_Type_Id
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    public Integer getInfoTypeId() {
        return infoTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_info_type.info_Type_Id
     *
     * @param infoTypeId the value for pro_info_type.info_Type_Id
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    public void setInfoTypeId(Integer infoTypeId) {
        this.infoTypeId = infoTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_info_type.productId
     *
     * @return the value of pro_info_type.productId
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_info_type.productId
     *
     * @param productid the value for pro_info_type.productId
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_info_type.typeId
     *
     * @return the value of pro_info_type.typeId
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_info_type.typeId
     *
     * @param typeid the value for pro_info_type.typeId
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }
}