package com.qf.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class Registcode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registcode.codeId
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    private Integer codeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registcode.Phone
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    private String userphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registcode.CodeMsg
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    private String codemsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registcode.date
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss" ,timezone = "GMT+8")
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registcode.codeId
     *
     * @return the value of registcode.codeId
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    public Integer getCodeid() {
        return codeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registcode.codeId
     *
     * @param codeid the value for registcode.codeId
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    public void setCodeid(Integer codeid) {
        this.codeid = codeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registcode.Phone
     *
     * @return the value of registcode.Phone
     *
     * @mbggenerated Thu Apr 18 11:06:59 CST 2019
     */
    public String getUserphone() {
        return userphone;
    }

    public void setUserphone(String userphone) {
        this.userphone = userphone;
    }

    public String getCodemsg() {
        return codemsg;
    }

    public void setCodemsg(String codemsg) {
        this.codemsg = codemsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registcode.date
     *
     * @return the value of registcode.date
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registcode.date
     *
     * @param date the value for registcode.date
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }
}