package com.qf.entity;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userId
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userName
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userRealName
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    private String userrealname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userPassword
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    private String userpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userPhone
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    private String userphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userHeadUrl
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    private String userheadurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sex
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.birthday
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userState
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    private Integer userstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.pwdSafety
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    private Integer pwdsafety;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userId
     *
     * @return the value of user.userId
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userId
     *
     * @param userid the value for user.userId
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userName
     *
     * @return the value of user.userName
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userName
     *
     * @param username the value for user.userName
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userRealName
     *
     * @return the value of user.userRealName
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public String getUserrealname() {
        return userrealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userRealName
     *
     * @param userrealname the value for user.userRealName
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public void setUserrealname(String userrealname) {
        this.userrealname = userrealname == null ? null : userrealname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userPassword
     *
     * @return the value of user.userPassword
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public String getUserpassword() {
        return userpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userPassword
     *
     * @param userpassword the value for user.userPassword
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public void setUserpassword(String userpassword) {
        this.userpassword = userpassword == null ? null : userpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userPhone
     *
     * @return the value of user.userPhone
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public String getUserphone() {
        return userphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userPhone
     *
     * @param userphone the value for user.userPhone
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public void setUserphone(String userphone) {
        this.userphone = userphone == null ? null : userphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userHeadUrl
     *
     * @return the value of user.userHeadUrl
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public String getUserheadurl() {
        return userheadurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userHeadUrl
     *
     * @param userheadurl the value for user.userHeadUrl
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public void setUserheadurl(String userheadurl) {
        this.userheadurl = userheadurl == null ? null : userheadurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sex
     *
     * @return the value of user.sex
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sex
     *
     * @param sex the value for user.sex
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.birthday
     *
     * @return the value of user.birthday
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.birthday
     *
     * @param birthday the value for user.birthday
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userState
     *
     * @return the value of user.userState
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public Integer getUserstate() {
        return userstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userState
     *
     * @param userstate the value for user.userState
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public void setUserstate(Integer userstate) {
        this.userstate = userstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.pwdSafety
     *
     * @return the value of user.pwdSafety
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public Integer getPwdsafety() {
        return pwdsafety;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.pwdSafety
     *
     * @param pwdsafety the value for user.pwdSafety
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    public void setPwdsafety(Integer pwdsafety) {
        this.pwdsafety = pwdsafety;
    }
}