package com.qf.mapper;

import com.qf.entity.Productappraise;
import com.qf.entity.ProductappraiseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductappraiseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productappraise
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    int countByExample(ProductappraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productappraise
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    int deleteByExample(ProductappraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productappraise
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    int deleteByPrimaryKey(Integer appraiseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productappraise
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    int insert(Productappraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productappraise
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    int insertSelective(Productappraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productappraise
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    List<Productappraise> selectByExample(ProductappraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productappraise
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    Productappraise selectByPrimaryKey(Integer appraiseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productappraise
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    int updateByExampleSelective(@Param("record") Productappraise record, @Param("example") ProductappraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productappraise
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    int updateByExample(@Param("record") Productappraise record, @Param("example") ProductappraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productappraise
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    int updateByPrimaryKeySelective(Productappraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productappraise
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    int updateByPrimaryKey(Productappraise record);
}