package com.qf.mapper;

import com.qf.entity.Productclass;
import com.qf.entity.ProductclassExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductclassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productclass
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    int countByExample(ProductclassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productclass
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    int deleteByExample(ProductclassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productclass
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    int deleteByPrimaryKey(Integer productclassid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productclass
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    int insert(Productclass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productclass
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    int insertSelective(Productclass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productclass
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    List<Productclass> selectByExample(ProductclassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productclass
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    Productclass selectByPrimaryKey(Integer productclassid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productclass
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    int updateByExampleSelective(@Param("record") Productclass record, @Param("example") ProductclassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productclass
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    int updateByExample(@Param("record") Productclass record, @Param("example") ProductclassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productclass
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    int updateByPrimaryKeySelective(Productclass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productclass
     *
     * @mbggenerated Thu Apr 18 09:23:53 CST 2019
     */
    int updateByPrimaryKey(Productclass record);
}