package com.qf.mapper;

import com.qf.entity.Producttype;
import com.qf.entity.ProducttypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProducttypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producttype
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    int countByExample(ProducttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producttype
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    int deleteByExample(ProducttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producttype
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    int deleteByPrimaryKey(Integer typeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producttype
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    int insert(Producttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producttype
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    int insertSelective(Producttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producttype
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    List<Producttype> selectByExample(ProducttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producttype
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    Producttype selectByPrimaryKey(Integer typeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producttype
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    int updateByExampleSelective(@Param("record") Producttype record, @Param("example") ProducttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producttype
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    int updateByExample(@Param("record") Producttype record, @Param("example") ProducttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producttype
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    int updateByPrimaryKeySelective(Producttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producttype
     *
     * @mbggenerated Thu Apr 18 10:34:30 CST 2019
     */
    int updateByPrimaryKey(Producttype record);
}