package com.qf.mapper;

import com.qf.entity.Productorder;
import com.qf.entity.ProductorderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductorderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productorder
     *
     * @mbggenerated Sun Apr 14 15:07:44 CST 2019
     */
    int countByExample(ProductorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productorder
     *
     * @mbggenerated Sun Apr 14 15:07:44 CST 2019
     */
    int deleteByExample(ProductorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productorder
     *
     * @mbggenerated Sun Apr 14 15:07:44 CST 2019
     */
    int deleteByPrimaryKey(Integer orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productorder
     *
     * @mbggenerated Sun Apr 14 15:07:44 CST 2019
     */
    int insert(Productorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productorder
     *
     * @mbggenerated Sun Apr 14 15:07:44 CST 2019
     */
    int insertSelective(Productorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productorder
     *
     * @mbggenerated Sun Apr 14 15:07:44 CST 2019
     */
    List<Productorder> selectByExample(ProductorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productorder
     *
     * @mbggenerated Sun Apr 14 15:07:44 CST 2019
     */
    Productorder selectByPrimaryKey(Integer orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productorder
     *
     * @mbggenerated Sun Apr 14 15:07:44 CST 2019
     */
    int updateByExampleSelective(@Param("record") Productorder record, @Param("example") ProductorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productorder
     *
     * @mbggenerated Sun Apr 14 15:07:44 CST 2019
     */
    int updateByExample(@Param("record") Productorder record, @Param("example") ProductorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productorder
     *
     * @mbggenerated Sun Apr 14 15:07:44 CST 2019
     */
    int updateByPrimaryKeySelective(Productorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productorder
     *
     * @mbggenerated Sun Apr 14 15:07:44 CST 2019
     */
    int updateByPrimaryKey(Productorder record);
}