package com.qf.mapper;

import com.qf.entity.ProInfoType;
import com.qf.entity.ProInfoTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProInfoTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_info_type
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    int countByExample(ProInfoTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_info_type
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    int deleteByExample(ProInfoTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_info_type
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    int deleteByPrimaryKey(Integer infoTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_info_type
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    int insert(ProInfoType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_info_type
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    int insertSelective(ProInfoType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_info_type
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    List<ProInfoType> selectByExample(ProInfoTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_info_type
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    ProInfoType selectByPrimaryKey(Integer infoTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_info_type
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    int updateByExampleSelective(@Param("record") ProInfoType record, @Param("example") ProInfoTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_info_type
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    int updateByExample(@Param("record") ProInfoType record, @Param("example") ProInfoTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_info_type
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    int updateByPrimaryKeySelective(ProInfoType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_info_type
     *
     * @mbggenerated Thu Apr 18 11:00:21 CST 2019
     */
    int updateByPrimaryKey(ProInfoType record);
}